paritytech/substrate-tip-bot

- .gitlab-ci.yml
- Dockerfile
- README.md
- helm/.gitignore
- helm/Chart.yaml
- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
- helm/values.yaml
- src/bot.ts
- src/github.ts
- src/tip.ts
- src/types.ts
@mordamax need your help here: what env variables should be added to helm? are there any secrets?
Close https://github.com/paritytech/ci_cd/issues/486
> [ci] Add helm chart

- .gitlab-ci.yml
Also changed deploy to k8s job so it's no needed to restart the whole pipeline for re-deploying the app
cc https://github.com/paritytech/ci_cd/issues/544
> [ci] deploy from new runners

- helm/values.yaml
- package.json
- src/bot.ts
- src/metrics.ts
- yarn.lock
Progresses https://github.com/paritytech/substrate-tip-bot/issues/20
> Add health and metrics

- src/chain-config.ts
> Refactor url construction

- .gitlab-ci.yml
To make it consistent with our other repos.
> Deploy to prod on release

- .gitlab-ci.yml
Follow up to https://github.com/paritytech/substrate-tip-bot/pull/51
Otherwise it seems like it won't get to the production without the previous stages.
> Add more stages to the release pipeline

- src/tip-opengov.ts
remove nonce + add few more logs to invalid transaction logs
> remove nonce + add few more logs to invalid transaction logs

- src/util.ts
- Progresses https://github.com/paritytech/substrate-tip-bot/issues/54
- Example: https://github.com/paritytech-stg/playground/pull/23#issuecomment-1564511236
> Display numeric value of named OpenGov tips

- src/bot.ts
- [Successful example](https://github.com/paritytech-stg/playground/pull/23#issuecomment-1564524277)
- [Unsuccessful example](https://github.com/paritytech-stg/playground/pull/23#issuecomment-1564523330)
- Closes https://github.com/paritytech/substrate-tip-bot/issues/67
> Add emoji reactions

- src/polkassembly/polkassembly-moonbase.test.ts
- src/tip-opengov.ts
- src/util.ts
- Progresses https://github.com/paritytech/substrate-tip-bot/issues/85
- Example Polkassembly post for preview: https://moonbase.polkassembly.network/referenda/39
> Use markdown for Polkassembly post content

- src/tip-opengov.ts
- Fixes issue from this comment: https://github.com/paritytech/substrate-tip-bot/pull/91#discussion_r1236858691
> Unsubscribe from transaction upon error

- .env.example
- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
- package.json
- src/bot.ts
- src/types.ts
- src/util.ts
- yarn.lock
Closes https://github.com/paritytech/substrate-tip-bot/issues/69
> Introduce Matrix notifications

- .env.example
- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
Closes https://github.com/paritytech/substrate-tip-bot/issues/96
> Remove obsolete variables

- .env.example
- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
Those variables are not used directly in code so we might be mistaken that they're not used, so adding comments.
> Add comments about variables not used directly in code

- src/bot.ts
- src/tip-opengov.e2e.ts
- src/util.test.ts
- src/util.ts
- Closes https://github.com/paritytech/substrate-tip-bot/issues/54
> Read the contributor address from their github profile (bio)

- src/bot.ts
- src/polkassembly/polkassembly-moonbase.test.ts
- src/polkassembly/polkassembly.test.ts
- src/polkassembly/polkassembly.ts
- src/testUtil.ts
- Progresses https://github.com/paritytech/substrate-tip-bot/issues/85
> Add more logs to Polkassembly integration

- src/bot-handle-comment.ts
Right now, on any other comment not mentioning the bot, we go through portions of code unnecessarily, while we could just return earlier.
> Skip early if not mentioned

- src/bot-handle-comment.ts
We do check for errors now.
https://github.com/paritytech/substrate-tip-bot/blob/88c74b31496c2273ceafd8143320d80853504ee5/src/tip-opengov.ts#L94
> Remove obsolete comment

- src/bot-handle-comment.ts
- src/matrix.ts
Closes https://github.com/paritytech/substrate-tip-bot/issues/114
> Don't tag the maintainers on known user errors

- .gitlab-ci.yml
Addresses https://github.com/paritytech/ci_cd/issues/916
> CI Update vault auth

- src/balance.ts
- src/chain-config.ts
- src/types.ts
Progresses https://github.com/paritytech/substrate-tip-bot/issues/46
> Add Westend and Rococo configurations

- src/util.ts
> Add more valid networks

- .github/workflows/keep-polkadot-cache.yml
Follow-up to https://github.com/paritytech/substrate-tip-bot/pull/144
> Update polkadot version in the cache-warming workflow

- .github/workflows/test-e2e.yml
- README.md
- polkadot.e2e.patch
- Had to regenerate the patch file.
> Update E2E tests to `v1.14.0`

- src/bot-handle-comment.ts
- src/polkassembly/polkassembly-moonbase.integration.ts
- src/tip-opengov.e2e.ts
- src/types.ts
- src/util.ts
> Correct PR link for other orgs
