paritytech/substrate-tip-bot

src/bot.ts
This env variable should be only used as an optional override
=> Fixing PRIVATE_KEY_BASE64

.gitlab-ci.yml, Dockerfile.README.md
Added CI job to publish Docker image description to [hub.docker.com](https://hub.docker.com/r/paritytech/substrate-tip-bot)
Description can be updated in a `Dockerfile.README.md` file in a repository root and as soon it will be merged into the `master` branch, its content will get published to [hub.docker.com](https://hub.docker.com/r/paritytech/substrate-tip-bot)
Related https://github.com/paritytech/ci_cd/issues/741
=> ci: Add CI job to publish docker image description to hub.docker.com

src/balance.ts, src/bot.ts, src/chain-config.ts, src/metrics.ts, src/tip-opengov.ts, src/tip-treasury.ts, src/tip.ts, src/types.ts, src/util.ts
- Add the balance to the metrics - progresses https://github.com/paritytech/substrate-tip-bot/issues/20
- Fetch balance for all networks on startup, and update it after tip requests
- Some necessary refactors around chain config - `tipUrl` is no longer part of `ChainConfig`, because it depends on a given tip instance
=> Add tip bot balance to metrics

README.md, src/bot.ts, src/chain-config.ts, src/metrics.ts, src/tip-opengov.ts, src/tip-treasury.ts, src/tip.test.ts, src/tip.ts, src/types.ts, src/util.ts
- Progresses https://github.com/paritytech/substrate-tip-bot/issues/39
- Automatically "detects" whether the target chain supports OpenGov or Treasury Tips
- This is done in a "dumb" way by specifying a chain config option. The reasoning is that soon, OpenGov will be added to Polkadot, and we will remove gov1 tips from the tip bot, only use OpenGov, and no "smart" detection mechanism will be needed.
- Now there is a single command - `/tip`. `/tip2` is no longer there.
- Updated integrations tests to use two chains.
=> Automatically "detect" the governance of the chain

src/bot.ts
- Instead of a single `const respondOnResult = async (result: string | Error | undefined`,
split it into a `respondOnResult` that handles known results and `respondOnUnknownError` that handles promise rejections.
- Move the github calling (`@${tipRequester}`) into the `onIssueComment` function - this allows as to close https://github.com/paritytech/substrate-tip-bot/issues/44
- Do not display an unknown error to the user - we will see it in logs.
=> Revamp the way that bot handles responding

src/tip.ts
Without that, when the API is not available, the bot hangs trying to connect forever and never responds back to the user.
With this change, the bot will post a comment about an error.
=> Throw on connection failure

.eslintrc.js, README.md, package.json, src/tip-opengov.ts, src/types.ts, yarn.lock
fix: #60, Check if preimage exists on chain before creating a proposal
First submit a preimage and wait until it's finalized in blockHash
then call `await api.query.preimage.statusFor(proposalHash);` so we can make sure the preimage is there
then only create a proposal with this preimage
**Bonus**: fixed wrong field in proposal length -> len in Lookup, as currently it sends nothing (thus defaults to 0) which makes proposals not executable
=> fix: #60, Check if preimage exists on chain before creating a proposal

README.md, jest.e2e.config.js, package.json, polkadot.e2e.patch, src/tip-opengov.e2e.ts
This introduces a test for an opengov tip, with a local Kusama node.
- First, we run a modified Kusama node.
- The modifications shorten the time of the referendum, and speed up treasury spend period. They are in a form of a git patch.
- Then, we send the tip proposal, vote `aye` with a different account, wait for all the phases to go through and assert the balance of the beneficiary.
- It is NOT run on CI. (maybe in the future?)
=> Introduce an E2E tests for an opengov tip

src/tip-opengov.ts
The `isError` is defined here:
https://github.com/polkadot-js/api/blob/edde226740341396bc59bf96ad38ea559357bb9d/packages/api/src/submittable/Result.ts#L69-L71
I just had an `isRetracted` status but the extrinsic eventually went through, so the current definition is incorrect.
=> Use polkadot.js getter to determine extrinsic error

src/tip-opengov.ts
The `result.status` turned out to be an object that prints out dozens of internal things, so it turned out to be a bad thing to log.
=> Remove a log that was too verbose

src/balance.ts
This might help with https://github.com/paritytech/substrate-tip-bot/issues/11
(Not closing, I'm going to observe it for a while because I don't have a way to consistently reproduce the error locally).
I believe the issue might have been fixed by adding a disconnect:
https://github.com/paritytech/substrate-tip-bot/blob/374ce68097fa063f2322b77964e73122d93cfba5/src/tip.ts#L32
And then re-introduced by adding a separate ApiPromise in the balance check without disconnecting.
=> Disconnect ApiPromise after balance check

package.json, src/bot-handle-comment.ts, src/matrix.ts, src/types.ts, yarn.lock
- [Extract github emoji logic into a helper function `githubEmojiReaction`](https://github.com/paritytech/substrate-tip-bot/commit/4c3eb907206aedd819650830827a3ae602ded918)
- [Extract the matrix notification logic into a separate file](https://github.com/paritytech/substrate-tip-bot/commit/7e11ca8d2af9d2a5ba3687df3d3b743f38e825fe)
- [Extract the error message of an unkown error into a variable, because it was duplicated](https://github.com/paritytech/substrate-tip-bot/commit/044e19f3fd064c0cffd76bfcec94ede8b40062fa)
- The goal is to improve the readability of the file
=> Various refactorings of the `bot-handle-comment.ts` file

src/bot-handle-comment.ts, src/tip.ts, src/types.ts, src/util.test.ts, src/util.ts
- There should be no behaviour change, only refactorings.
- Having previously removed the `"skip"` type of a result type, we can now change the result type to a simple boolean and change the `switch` statement into a simple `if-else`.
- Change the `handleTipRequest.then().catch()` construct into a `try-catch`, for a more top-to-bottom reading experience.
=> Refactor the flow of `bot-handle-comment.ts`

src/tip-opengov.ts, src/tip.integration.ts, src/util.ts
Previously we were calculating the byte size of strings, without taking into account that those are hexes.
=> Update the way we calculate byte size of the proposals

README.md, src/chain-config.ts, src/tip-opengov.e2e.ts
At current USD prices,
- a small KSM tip is $38.46 and a small DOT tip is $82.77
- a medium KSM tip is $95.3 and a medium DOT tip is $334.4
- a large KSM tip is $152.48 and a large DOT tip is $606
I don't think it makes sense for the purchasing power of the same 'size' tip to differ so drastically depending on the network being tipped on.
1 KSM is approximately 5 DOT at current prices, so I've updated the KSM tip sizes to be 1/5 of the DOT sizes. This is not perfect, but better than the current situation.
=> Normalise DOT/KSM tip size purchasing power

src/polkassembly/polkassembly.ts
As of [this change](https://github.com/polkassembly/polkassembly/pull/1111), a `topicId` has become a necessary parameters of editing a post.
I'm not sure which topic to choose - selected `general` without strong opinion.
This fixes https://github.com/paritytech/substrate-tip-bot/issues/132
Tested on Moonbase alpha: https://moonbase.polkassembly.network/referenda/61
---
=> Add topic to edited post

.github/workflows/keep-polkadot-cache.yml
This repo has infrequent PR, which cause the Polkadot build cache to expire (after 7 days).
The build cache takes a long time to build, so it is worth to go the extra step to preserve it.
This workflow will download the cache every 6 days, in order to keep it warm and preserve it from being removed automatically by Github.
=> Keep Polkadot cache warm

.gitlab-ci.yml
Fix for https://github.com/paritytech/substrate-tip-bot/pull/139 ([CI Job](https://gitlab.parity.io/parity/mirrors/substrate-tip-bot/-/jobs/5139204))
argocd token only available if environment is set.
=> ci: fix argocd-deployment

.github/workflows/keep-polkadot-cache.yml, .github/workflows/test.yml, README.md, polkadot.e2e.patch, src/tip-opengov.e2e.ts, src/tip.integration.ts, src/util.ts
An update after this change: https://github.com/paritytech/polkadot-sdk/pull/1333
- Update Polkadot version in E2E and integration tests to `v1.7.1`.
- Use Rococo and Westend instead of Polkadot and Kusama local dev chains (since they have been moved out).
- In E2E tests, fund the treasury - it is now empty when you start a dev chain.
=> Update treasury extrinsic

src/bot-handle-comment.ts, src/tip-opengov.ts, src/tip.ts, src/util.ts
Closes https://github.com/paritytech/substrate-tip-bot/issues/150
If the user is not in the privileged GitHub team, the bot will try to produce a tip referendum creation link instead.
To achieve it, I extracted some functionality like preparing an extrinsic to separate functions.
If it works, it looks [like this](https://github.com/paritytech-stg/playground/pull/24#issuecomment-2072688642).
If there is an issue with generating the PolkadotJS-Apps link, it will fall back to a message without, [like this](https://github.com/paritytech-stg/playground/pull/24#issuecomment-2072166849).
=> Tip referendum creation link

helm/Chart.yaml, helm/values-parity-prod.yaml, helm/values-parity-stg.yaml, helm/values.yaml
Part of https://github.com/paritytech/devops/issues/3323
=> Move charts to its application repos

.github/workflows/test-e2e-cron.yml
Currently, it was taking 1.9.0 as the last one from:
```
polkadot-v1.1.0
polkadot-v1.10.0
polkadot-v1.11.0
polkadot-v1.12.0
polkadot-v1.2.0
polkadot-v1.3.0
polkadot-v1.4.0
polkadot-v1.5.0
polkadot-v1.5.0-nix
polkadot-v1.6.0
polkadot-v1.7.0
polkadot-v1.7.1
polkadot-v1.7.2
polkadot-v1.8.0
polkadot-v1.9.0
```
=> Use version sort when determining the latest Polkadot release

src/bot-handle-comment.ts
Quick temporary fix for https://github.com/paritytech/substrate-tip-bot/issues/170
=> Disable referendum link creation

README.md, package.json, src/bot-handle-comment.ts, src/tip-opengov.ts, src/tip.integration.ts, src/tip.ts, yarn.lock
When we migrated to papi, we've introduced a bug, where a tip link with
encoded extrinsic was a signed transaction hash instead. Fixed.
Another change is upgrading testcontainers that recently got an option
of starting container with platform, which finally allows not to compile
polkadot container locally.
Fixes #168 #170
=> Fixing tip links

.github/workflows/test-e2e-cron.yml
The `polkadot-v*` tags are still there, but they will go away so we might as well change it now.
=> Use `polkadot-stable*` tags for cron-bases E2E tests

.github/workflows/test-e2e-cron.yml
We better use the most recent, but stable release for out tests - there is no need to test prerelease here.
=> Don't use prerelase versions for E2E tests

jest.integration.config.js, package.json, src/bot-handle-comment.ts, src/tip.integration.ts, yarn.lock
tip-bot can be installed as an app to a multitude of orgs, but one
app means one server and one approvers org/team.
Querying approvers should be done via installation token of approvers
org, while leaving comments should be done by installation token of
repository, where the PR that's being tipped was opened.
Fixes #169
=> Using correct tokens for multi org setup

src/bot-handle-comment.ts, src/tip.integration.ts
Not everyone recognizes that paritytech/tip-bot-approvers is actually a
team, not a repo. Using a link might clarify it.
Fixes #167
=> Using an org link for "only members of..." comment

src/util.test.ts, src/util.ts
First interaction from the bot with new users should be friendly, not some error message. [Example](https://github.com/paritytech/polkadot-sdk/pull/7600#issuecomment-2687884819)
Can we check that the message formats correctly?
=> More friendly first tip message
